name: Doufexis
favicon: null
layout_spectrum: 0.8633591756224632
typography_spectrum: 0.4924826107453555
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6053541181609035
  lightness: 0.5361195101868361
  saturation: 0.36603432544507086
  rhythmicContrast: 0.6293078281451017
purpose: []
